spring.application.name=ms-pedidos360-bff

#y este tenia el 8080 pero en los puertos mi amigo se confundio
server.port=8083

# Microsoft Entra ID - OAuth2 Resource Server
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/5daa7f18-0c54-4c12-907d-3560ac33fa04/v2.0
##Esta con el entraId de Gonzalo
spring.security.oauth2.resourceserver.jwt.audiences=902a3d3f-c37d-4d43-8725-dca7f90fe474

# Microservicios (este tenia 8081)
services.catalog.url=http://localhost:8081

## aqui era 8083 pero lo cambie
services.orders.url=http://localhost:8080

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.oauth2=DEBUG