spring.application.name=ms-pedidos360-bff

#y este tenia el 8080 pero en los puertos mi amigo se confundio
server.port=8083

# Microsoft Entra ID - OAuth2 Resource Server
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/5daa7f18-0c54-4c12-907d-3560ac33fa04/v2.0
spring.security.oauth2.resourceserver.jwt.audiences=12436eae-83da-42c9-a70d-4c9e7bccb7f1

# Microservicios (este tenia 8081)
services.catalog.url=http://localhost:8080

## aqui era 8083 pero lo cambie
services.orders.url=http://localhost:8081

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.oauth2=DEBUG